# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: install ci cd
        run: npm ci
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: npm run build --if-present
      - name: Run test
        run: npm test
      - name: run test
        run: npm test
      - name: Create folder
        run: |
          mkdir deploy
      - name: run npm build dist command to copy files from build folder
        run: npm run build-dist
        working-directory: deploy
      - name: deployqb
        run: |
          sudo npm install -g deployqb
          deployqb init 'bsrb9fvi6' 'att' 'dzpnst5dxwq3pdbuivbaybiuqp9x' 'b7j53i_ntdu_0_b2yunpcddmg9pjd58g7kvdnhtrfs' '665' '' 'ATNT-GITHUB_ACTION_Prod' '' 'no'
      - name: deployqb to env
        run: deployab feat
